services:
  apidb:
    container_name: 'apidatabase'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pbdatabase'
      - 'MYSQL_PASSWORD=Numsey@Password!'
      - 'MYSQL_ROOT_PASSWORD=Numsey@Password!!'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'

  api:
    container_name: 'apibloco_container'
    image: 'apibloco:latest'
    ports:
      - 8086:8086 
    restart: unless-stopped

  rabbitmq:
    container_name: 'rabbit'
    image: 'rabbitmq:3.13.7-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'    
      
  axioniq:
    container_name: 'axionapiserver'
    image: 'axoniq/axonserver:2024.1.2-jdk-17-nonroot'
    ports:
      - 8024:8024
      - 8124:8124

  eureka:
    container_name: 'eureka_server'
    image: 'eureka:latest'
    ports:
      - 8761:8761




        